{{- if .Values.kafkaBackup.aws -}}
apiVersion: v1
kind: Secret
metadata:
  name: kafka-dr
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "app.labels" $ | indent 4 }}
data:
  {{- if .Values.kafkaBackup.aws.credentials }}
  credentials: {{ .Values.kafkaBackup.aws.credentials | b64enc }}
  {{- end }}
{{- end -}}
