kafkaTopicBackup:
  image:
    repository: docker-pipeline-upstream-mirror.dr-uw2.adobeitc.com/kafka-dr
    pullPolicy: IfNotPresent
    tag: 1.0.1
  imagePullSecrets:
  - docker-pipeline-upstream-mirror

  connectEndpoint: "http://kafka-s3-backup-pipeline-dr-kafka-1:8083"
  config:
    global:
      connector.class: "com.spredfast.kafka.connect.s3.sink.S3SinkConnector"
      s3.bucket: "pip-fab-test-dr-dev"
      local.buffer.dir: "/tmp/s3"
    topics:
      totalusagereport:
        tasks.max: 10
        flush.size: 100000
