apiVersion: v1
appVersion: "1.0"
description: Kafka S3 Backup
name: ${chartName}
version: ${chartVersion}

maintainers:
    - name: falca

home: https://github.com/adobe/kafka-connect-s3

sources:
    - https://github.com/adobe/kafka-connect-s3

keywords:
    - kafka
    - kafka connect
    - S3
