#  Copyright 2020 Adobe. All rights reserved.
#  This file is licensed to you under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License. You may obtain a copy
#  of the License at http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software distributed under
#  the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
#  OF ANY KIND, either express or implied. See the License for the specific language
#  governing permissions and limitations under the License.

kafkaBackup:
  # aws:
  #   credentials: |
  #     [default]
  #     aws_access_key_id=KEY_ID_HERE
  #     aws_secret_access_key=ACCESS_KEY_HERE
  #     region=us-east-1


  connect:
    restPort: 8083
    workersCount: 1
    workerConfigs:
      client.id: "connect-backup"
      bootstrap.servers: localhost:9096
      plugin.path: "/etc/kafka-backup-libs/connectors"
      group.id: "connect-backup"
      key.converter: "com.spredfast.kafka.connect.s3.AlreadyBytesConverter"
      value.converter: "com.spredfast.kafka.connect.s3.AlreadyBytesConverter"
      config.storage.topic: "__backup_configs"
      offset.storage.topic: "__backup_offsets"
      status.storage.topic: "__backup_status"
      task.shutdown.graceful.timeout.ms: "30000"
      producer.acks: "1"
      offset.flush.timeout.ms: "10000"

  deployment:
    resources:
      requests:
        cpu: 4
        memory: 6Gi
      limits:
        cpu: 4
        memory: 6Gi

  image:
    kafka:
      repository: "adobe/kafka"
      tag: "2.12-2.5.1"
    backup:
      repository: "docker-pipeline-release.dr-uw2.adobeitc.com/kafka-s3-backup-libs"
      tag: "v0.4.3-f0cb2d5"
    pullSecret: itc-docker-secret

  podmonitor:
    enabled: false
